CREATE TABLE users (
    id bigint generated by default as identity PRIMARY KEY, -- 고유 식별자
    username VARCHAR(50) UNIQUE NOT NULL, -- 아이디
    password VARCHAR(100) NOT NULL, -- 비밀번호
    role VARCHAR(20) NOT NULL, -- 구매자(buyer), 판매자(seller), admin 역할 구분
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 자동으로 생성 날짜 추가
);

CREATE TABLE products (
    product_id bigint generated by default as identity PRIMARY KEY, -- 고유 식별자
    seller_name VARCHAR(50) NOT NULL, -- 판매자 아이디
    product_name VARCHAR(100) NOT NULL,
    shipping_fee INT NOT NULL,
    price INT NOT NULL,
    rating DECIMAL(3, 2) NOT NULL,
    review_count INT NOT NULL,
    image_path VARCHAR(255),

    CONSTRAINT fk_seller
        FOREIGN KEY (seller_name) REFERENCES users(username)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ratings (
    product_id bigint generated by default as identity PRIMARY KEY, -- 고유 식별자
    rating DECIMAL(3, 2) NOT NULL,
    review_content VARCHAR(300),

    CONSTRAINT fk_product_id
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);