CREATE TABLE users (
    id bigint generated by default as identity PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id bigint generated by default as identity PRIMARY KEY,
    seller_name VARCHAR(50) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    shipping_fee INT NOT NULL,
    price INT NOT NULL,
    count INT NOT NULL,
    rating DECIMAL(3, 2) NOT NULL,
    review_count INT NOT NULL,
    image_path VARCHAR(255),

    CONSTRAINT fk_seller
        FOREIGN KEY (seller_name) REFERENCES users(username)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ratings (
    product_id bigint generated by default as identity PRIMARY KEY,
    rating DECIMAL(3, 2) NOT NULL,
    review_content VARCHAR(300),

    CONSTRAINT fk_product_id
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE carts (
    cart_id bigint generated by default as identity PRIMARY KEY,
    user_id bigint NOT NULL,

    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE cartItems (
    cart_item_id bigint generated by default as identity PRIMARY KEY,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    count int NOT NULL,

    CONSTRAINT fk_cart_id
        FOREIGN KEY (cart_id) REFERENCES carts(cart_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_product_id
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
